title: Lazygames
description: Game concepts and ideas
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Update these if your repository owner/name differ
url: https://lazyville.github.io
baseurl: /lazygames
